// Code generated by go-swagger; DO NOT EDIT.

package url

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteURLHandlerFunc turns a function with the right signature into a delete Url handler
type DeleteURLHandlerFunc func(DeleteURLParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteURLHandlerFunc) Handle(params DeleteURLParams) middleware.Responder {
	return fn(params)
}

// DeleteURLHandler interface for that can handle valid delete Url params
type DeleteURLHandler interface {
	Handle(DeleteURLParams) middleware.Responder
}

// NewDeleteURL creates a new http.Handler for the delete Url operation
func NewDeleteURL(ctx *middleware.Context, handler DeleteURLHandler) *DeleteURL {
	return &DeleteURL{Context: ctx, Handler: handler}
}

/*DeleteURL swagger:route DELETE /url/{shortURL} Url deleteUrl

Delete a already existing url. The only argument that is requested is the shortURL to be deleted.

*/
type DeleteURL struct {
	Context *middleware.Context
	Handler DeleteURLHandler
}

func (o *DeleteURL) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteURLParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
