// Code generated by go-swagger; DO NOT EDIT.

package url

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteURLParams creates a new DeleteURLParams object
// no default values defined in spec.
func NewDeleteURLParams() DeleteURLParams {

	return DeleteURLParams{}
}

// DeleteURLParams contains all the bound params for the delete Url operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteUrl
type DeleteURLParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Short URL to be passed to retrieve long URL
	  Required: true
	  In: path
	*/
	ShortURL string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteURLParams() beforehand.
func (o *DeleteURLParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rShortURL, rhkShortURL, _ := route.Params.GetOK("shortURL")
	if err := o.bindShortURL(rShortURL, rhkShortURL, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindShortURL binds and validates parameter ShortURL from path.
func (o *DeleteURLParams) bindShortURL(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ShortURL = raw

	return nil
}
