on:
  release:
    types:
      - released

# See https://docs.github.com/en/actions/using-jobs/using-concurrency
name: Release
jobs:
  release-name-check:
    if: ${{ !startsWith(github.event.release.tag_name, 'chart/') }}
    runs-on: ubuntu-latest
    steps:
     - run: echo "prereleasing since it is not a chart related tag"
  build:
    needs: [release-name-check]
    runs-on: ubuntu-latest
    name: Upload to S3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
