// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Shorturl shorturl
//
// swagger:model shorturl
type Shorturl struct {

	// shorneted URL
	// Required: true
	Shorturl *string `json:"shorturl"`
}

// Validate validates this shorturl
func (m *Shorturl) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateShorturl(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Shorturl) validateShorturl(formats strfmt.Registry) error {

	if err := validate.Required("shorturl", "body", m.Shorturl); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Shorturl) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Shorturl) UnmarshalBinary(b []byte) error {
	var res Shorturl
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
